package com.example.remotecompose.demo

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/actions.rc`, generated by `buildActionsSample()` in `Main.kt` via
 * `./gradlew :tools:rc-writer:run --args="actions"`: four buttons whose `MODIFIER_CLICK` action
 * lists change a float, a string and an integer, or call a `HOST_ACTION`. The panel and label
 * below them read those values, so tapping visibly changes the next frame.
 * `ActionsFixtureTest` asserts the behaviour; this copy makes it tappable on device.
 */
@OptIn(ExperimentalEncodingApi::class)
val ACTIONS_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAAMgAAADIAAAAAAAAAABmAAAAKgAAAAdhY3Rpb25zZwAAACpQAAAAK0IgAABmAAAALAAAAAx0YXAgYSBidXR0b26MAAAALQAA" +
            "AADM/////v////8AAAACAAAABEEgAAAQAAAAAX/AAABDAAAAAX/AAAA6QUAAAEFAAABBQAAAQUAAAMn////9y/////z/////AAAAAQAAAAJBAAAAyf//" +
            "//vK////+v////8AAAACAAAAAhAAAAAAQlAAAEMAAAAAQeAAADcAAAAAAAAAAAAAAAAAAAAAPfDw8T8IiIk/ZeXmP4AAAAAAAAA73gAAACtDFgAAZgAA" +
            "AC4AAAAEd2lkZdUAAAAsAAAALtbJ////+WYAAAAvAAAABFdpZGVmAAAAMAAAAADQ////+P////8AAAAv/////0EwAAAAAAAAQ8gAAAAAADAAAAABAAAA" +
            "AQAAAAHJ////99bW1tbK////9v////8AAAACAAAAAhAAAAAAQlAAAEMAAAAAQeAAADcAAAAAAAAAAAAAAAAAAAAAPoaGhz8goKE+jo6PP4AAAAAAAAA7" +
            "3gAAACtCIAAAZgAAADEAAAAGbmFycm931QAAACwAAAAx1sn////1ZgAAADIAAAAGTmFycm930P////T/////AAAAMv////9BMAAAAAAAAEPIAAAAAAAw" +
            "AAAAAQAAAAEAAAAByf////PW1tbW1tbL////8v////8AAAABAAAAAkEAAADJ////8cr////w/////wAAAAIAAAACEAAAAABCUAAAQwAAAABB4AAANwAA" +
            "AAAAAAAAAAAAAAAAAAA/e/v8PwyMjQAAAAA/gAAAAAAAADvUAAAALQAAAAfWyf///+9mAAAAMwAAAAVDb3VudND////u/////wAAADP/////QTAAAAAA" +
            "AABDyAAAAAAAMAAAAAEAAAABAAAAAcn////t1tbW1sr////s/////wAAAAIAAAACEAAAAABCUAAAQwAAAABB4AAANwAAAAAAAAAAAAAAAAAAAAA/Do6P" +
            "PhCQkT8qqqs/gAAAAAAAADvRAAAAKtbJ////62YAAAA0AAAABEhvc3TQ////6v////8AAAA0/////0EwAAAAAAAAQ8gAAAAAADAAAAABAAAAAQAAAAHJ" +
            "////6dbW1tbW1sr////o/////wAAAAEAAAAEEAAAAAD/gAArQwAAAABB8AAANwAAAAAAAAAAAAAAAAAAAAA+XNzdPo6Ojz6enp8/gAAAAAAAAMn////n" +
            "1tbQ////5v////8AAAAs/xojfkFgAAAAAAAAQ8gAAAAAADAAAAABAAAAAQAAAAHJ////5dbW1tY="
    )
}
