package com.example.remotecompose.demo

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/advanced.rc`, generated by `buildAdvancedSample()` in `Main.kt` via
 * `./gradlew :tools:rc-writer:run --args="advanced"`: bars sized by a float function called twice,
 * and paths sampled from float expressions in cartesian and polar form. `AdvancedFixtureTest`
 * asserts what it decodes to.
 */
@OptIn(ExperimentalEncodingApi::class)
val ADVANCED_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAAMgAAADIAAAAAAAAAABmAAAAKgAAAAhhZHZhbmNlZGcAAAAqqAAAACsAAAACAAAALAAAAC1RAAAALgAAAAP/gAAs/4AALf+xAAPW" +
            "KAAAAAIAAAAE/x6I5aYAAAArAAAAAkHwAABAgAAAUQAAAC8AAAAD/4AALkFAAAD/sQABKkFAAABBQAAA/4AAL0HQAAAoAAAAAgAAAAT/Q6BHpgAAACsAAAAC" +
            "QXAAAECAAABRAAAAMAAAAAP/gAAuQUAAAP+xAAEqQUAAAEHwAAD/gAAwQjAAAMEAAAAxAAAAAAAAAABAyQ/bQYAAAAAAAAX/sQBGQcgAAP+xAANBoAAA/7EA" +
            "AQAAAAj/sQBGQAAAAP+xAAP/sQASQaAAAP+xAANDAgAA/7EAASgAAAAFAAAABP/lOTUAAQAIAAAABUBAAAB8AAAAMcEAAAAyAAAACQAAAABAyQ/bQiAAAAAA" +
            "AAj/sQBGQKAAAP+xAAP/sQASQQAAAP+xAANB0AAA/7EAAQAAAAJCyAAAQqAAACgAAAADAAAABP+OJKoAAAAIfAAAADLBAAAAMwAAAAQAAAAAQMkP20GAAAAA" +
            "AAAF/7EARkHIAAD/sQADQaAAAP+xAAEAAAAI/7EARkAAAAD/sQAD/7EAEkFAAAD/sQADQzQAAP+xAAEoAAAABQAAAAT/N0dPAAEACAAAAAVAAAAAfAAAADM="
    )
}
