package com.example.remotecompose.demo

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/lazylist.rc`, generated by `buildLazyListSample()` in `Main.kt` via
 * `./gradlew :tools:rc-writer:run --args="lazylist"`: five hundred rows, of which only the dozen
 * in view are ever built.
 *
 * The rows are written once inside a loop, and a conditional draws one only when it is near the
 * window. A conditional that does not hold skips its block outright, so a row out of view costs
 * its arithmetic and nothing else — which is why five hundred rows fit in under a kilobyte.
 */
@OptIn(ExperimentalEncodingApi::class)
internal val LAZYLIST_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAASwAAAGkAAAAAAAAAABmAAAAKgAAAAhsYXp5bGlzdGcAAAAqUAAAACsAAAAAzP////7/////AAAAAQAAAARAwAAAEAAAAAF/wAAA" +
            "QwAAAAF/wAAANwAAAAAAAAAAAAAAAAAAAAA9kJCRPYCAgT3Q0NE/gAAAAAAAADpBgAAAQYAAAEGAAABBgAAAyf////1mAAAALAAAAAg1MDAgcm93c2YAAAAt" +
            "AAAAAND////8/////wAAACz/7ef2QbAAAAAAAABELwAAAAAALQAAAAEAAAABAAAAAcn////71tZRAAAALgAAAAT/gAArQmAAAP+xAAT/sQAOZgAAAC8AAAAJ" +
            "ZnJvbSByb3cghwAAADD/gAAuAAMAAAAAAAWIAAAAMQAAAC8AAAAwZgAAADIAAAAZIOKAlCBvbmx5IHRoZXNlIGFyZSBidWlsdIgAAAAzAAAAMQAAADLQ////" +
            "+v////8AAAAz/5yWrUFAAAAAAAAAQ8gAAAAAAC0AAAABAAAAAQAAAAHJ////+dbWzP////j/////AAAAAQAAAAQAAAAAEAAAAAF/wAAAQwAAAABDsgAAbOIA" +
            "AAAA/4AAK/+AADT/gAA1nQAAACsAAAAAAAAAAP+AADQAAAAAAAAAAwAAAAP/gAAOv4AAAP+xAAMAAAAAAAAAANbJ////98r////2/////wAAAAEAAAACEAAA" +
            "AAF/wAAAQwAAAABG2sAAyf////XXAAAANgAAAAA/gAAAQ/oAAFEAAAA3AAAACv+AADZCYAAA/7EAA0HgAAD/sQAB/4AAK/+xAAJDMgAA/7EAAv+xAAqyAv+A" +
            "ADdDTgAAUQAAADgAAAAD/4AANkJgAAD/sQADUQAAADkAAAAD/4AAOEJAAAD/sQABKAAAAAMAAAAE/x0aJgAAAAgzAAAAAP+AADhDhgAA/4AAOUFAAABBQAAA" +
            "UQAAADoAAAAD/4AAOEHwAAD/sQABUQAAADsAAAAD/4AAOEIQAAD/sQABUQAAADwAAAAH/4AANkIUAAD/sQAFQMAAAP+xAANB8AAA/7EAASgAAAACAAAABP9n" +
            "UKQzQYAAAP+AADr/gAA8/4AAO0BAAABAQAAAZgAAAD0AAAAEUm93IIcAAAA+/4AANgADAAAAAAAFiAAAAD8AAAA9AAAAPigAAAAEAAAABP/t5/YAAAABQXAA" +
            "AFEAAABAAAAAA/+AADhBoAAA/7EAAYUAAAA/QYAAAP+AAEC/gAAAAAAAAAAAAADW1tbW1tbW1g=="
    )
}
