package com.example.remotecompose.demo

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/list.rc`, generated by `buildListSample()` in `Main.kt` via
 * `./gradlew :tools:rc-writer:run --args="list"`: a row written once and expanded per entry of an
 * id list by `MACRO_FOR_EACH`. `MacroFixtureTest` asserts each entry gets its own row.
 */
@OptIn(ExperimentalEncodingApi::class)
val LIST_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAAPAAAADIAAAAAAAAAABmAAAAKgAAAARsaXN0ZwAAACpmAAAAKwAAAAhFc3ByZXNzb2YAAAAsAAAAB0NvcnRhZG9mAAAALQAAAApG" +
            "bGF0IHdoaXRlZgAAAC4AAAAGRmlsdGVykgAgACoAAAAEAAAAKwAAACwAAAAtAAAALsz////+/////wAAAAEAAAAEQQAAABAAAAABf8AAAEMAAAABf8AAADpB" +
            "gAAAQYAAAEGAAABBgAAAyf////1mAAAAMAAAAARNZW51ZgAAADEAAAAA0P////z/////AAAAMP8aI35BoAAAAAAAAEPIAAAAAAAxAAAAAQAAAAEAAAAByf//" +
            "//vW1vQAIAAqAAAAL8v////6/////wAAAAEAAAACAAAAABAAAAABf8AAAEMAAAAAQeAAADcAAAAAAAAAAAAAAAAAAAAAP2jo6T9q6us/dvb3P4AAAAAAAAA6" +
            "QQAAAAAAAABBAAAAAAAAAMn////50P////j/////AAAAL/8oNZNBYAAAAAAAAEPIAAAAAAAxAAAAAQAAAAEAAAAByf////fW1tbW1tbW"
    )
}
