package com.example.remotecompose.demo

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/showcase.rc` (generated by `Main.kt`'s `buildShowcase()`, run via
 * `./gradlew :tools:rc-writer:run --args="showcase"`) — a real `.rc` "dashboard card" UI, built to
 * demonstrate this renderer's real Column/Row arrangement and alignment-mode support (unlike
 * [SAMPLE_RC_BYTES], which is a dense grid of isolated opcode-coverage probes, not meant to look
 * like anything).
 *
 * A title, a row of three stat cards (a colored icon circle + a value + a label, each in its own
 * nested `startColumn`/`endColumn` wrapped in a `startBox`/`endBox` carrying a real `background()`
 * modifier) laid out with `RowLayout.SPACE_EVENLY`/`.CENTER` against a real declared `width()`, a
 * subtitle, and a row of four different-radius "avatar" circles laid out with `.SPACE_BETWEEN`/
 * `.CENTER`. Every child at every nesting level is deliberately drawn at placeholder/overlapping
 * local coordinates in the source document (the three stat cards' inner content all starts at the
 * same local origin; the avatar circles are all centered at their own `(radius, radius)`) — every
 * bit of the final on-screen layout comes from this renderer's own arrangement code, not
 * document-authored placement. Shared by every platform demo entry point so they render
 * byte-identical input, same rationale as [SAMPLE_RC_BYTES].
 */
@OptIn(ExperimentalEncodingApi::class)
val SHOWCASE_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAAWgAAAGkAAAAAAAAAABmAAAAKgAAAAhzaG93Y2FzZWcAAAAqzP////7/////AAAAAAAAAABBkAAAyf////3K/////P////8A" +
            "AAAAAAAAAMn////7KAAAAAIAAAAE/xojfmYAAAArAAAACURhc2hib2FyZIUAAAArQaAAAEGgAAAAAAAAAAAAAAAAAADW1sr////6/////wAAAAAAAAAA" +
            "EAAAAABDpAAAyf////nL////+P////8AAAAHAAAAAgAAAADJ////98r////2/////wAAAAAAAAAANwAAAAAAAAAAAAAAAAAAAAA/Y+PkP3Ly8z99/f4/" +
            "gAAAAAAAAMn////1zP////T/////AAAAAgAAAABAwAAAyf////PK////8v////8AAAAAAAAAAMn////xKAAAAAIAAAAE/x6I5S5BIAAAQSAAAEEgAADW" +
            "1sr////w/////wAAAAAAAAAAyf///+8oAAAAAgAAAAT/GiN+ZgAAACwAAAADMTI4hQAAACwAAAAAAAAAAAAAAAAAAAAAAAAAANbWyv///+7/////AAAA" +
            "AAAAAADJ////7SgAAAACAAAABP9UbnpmAAAALQAAAAVVc2Vyc4UAAAAtAAAAAAAAAAAAAAAAAAAAAAAAAADW1tbW1tbK////7P////8AAAAAAAAAADcA" +
            "AAAAAAAAAAAAAAAAAAAAP2jo6T919fY/aenqP4AAAAAAAADJ////68z////q/////wAAAAIAAAAAQMAAAMn////pyv///+j/////AAAAAAAAAADJ////" +
            "5ygAAAACAAAABP9DoEcuQYAAAEGAAABBgAAA1tbK////5v////8AAAAAAAAAAMn////lKAAAAAIAAAAE/xojfmYAAAAuAAAAAjQyhQAAAC4AAAAAAAAA" +
            "AAAAAAAAAAAAAAAAANbWyv///+T/////AAAAAAAAAADJ////4ygAAAACAAAABP9UbnpmAAAALwAAAAZPcmRlcnOFAAAALwAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAA1tbW1tbWyv///+L/////AAAAAAAAAAA3AAAAAAAAAAAAAAAAAAAAAD+AAAA/c/P0P2Dg4T+AAAAAAAAAyf///+HM////4P////8AAAACAAAAAEDA" +
            "AADJ////38r////e/////wAAAAAAAAAAyf///90oAAAAAgAAAAT/+4wALkFQAABBUAAAQVAAANbWyv///9z/////AAAAAAAAAADJ////2ygAAAACAAAA" +
            "BP8aI35mAAAAMAAAAAM5NyWFAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAA1tbK////2v////8AAAAAAAAAAMn////ZKAAAAAIAAAAE/1RuemYAAAAxAAAA" +
            "BlVwdGltZYUAAAAxAAAAAAAAAAAAAAAAAAAAAAAAAADW1tbW1tbW1tbWyv///9j/////AAAAAAAAAADJ////1ygAAAACAAAABP8aI35mAAAAMgAAAAhB" +
            "Y3Rpdml0eYUAAAAyQaAAAEGgAAAAAAAAAAAAAAAAAADW1sr////W/////wAAAAAAAAAAEAAAAABDpAAAyf///9XL////1P////8AAAAGAAAAAgAAAADJ" +
            "////08r////S/////wAAAAAAAAAAyf///9EoAAAAAgAAAAT/5Tk1LkEgAABBIAAAQSAAANbWyv///9D/////AAAAAAAAAADJ////zygAAAACAAAABP+O" +
            "JKouQYAAAEGAAABBgAAA1tbK////zv////8AAAAAAAAAAMn////NKAAAAAIAAAAE/wCJey5BQAAAQUAAAEFAAADW1sr////M/////wAAAAAAAAAAyf//" +
            "/8soAAAAAgAAAAT//dg1LkEAAABBAAAAQQAAANbW1tbW1tbW"
    )
}
