package com.example.remotecompose.demo

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/textpath.rc`, generated by `buildTextPathSample()` in `Main.kt` via
 * `./gradlew :tools:rc-writer:run --args="textpath"`: text laid along a cubic wave and around a
 * circle inside and out, a bar sized by `TEXT_MEASURE`, and a marker gated by
 * `CONDITIONAL_OPERATIONS`. `TextPathFixtureTest` asserts the placement.
 */
@OptIn(ExperimentalEncodingApi::class)
internal val TEXTPATH_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAAMgAAADIAAAAAAAAAABmAAAAKgAAAAh0ZXh0cGF0aGcAAAAqewAAACsAAAAM/4AACkEgAABCIAAA/4AADgAAAAAAAAAAQkgA" +
            "AECgAABCyAAAQoIAAEMWAABByAAAKAAAAAQAAAAE/x6I5QAAAAFBUAAAZgAAACwAAAAQZm9sbG93aW5nIGEgd2F2ZTUAAAAsAAAAKwAAAABAgAAAKAAA" +
            "AAQAAAAE/7C+xQAAAAFBEAAAZgAAAC0AAAAMb2Zmc2V0IGJlbG93NQAAAC0AAAArQWAAAEEAAAAoAAAABAAAAAT/Q6BHAAAAAUFAAABmAAAALgAAABBP" +
            "VVRTSURFIFRIRSBSSU5HOQAAAC5CyAAAQvAAAEI0AABDhwAAAAAAAAEAKAAAAAQAAAAE/+U5NQAAAAFBIAAAZgAAAC8AAAAPaW5zaWRlIHRoZSByaW5n" +
            "OQAAAC9CyAAAQvAAAEIAAABCtAAAAAAAAAEBZgAAADAAAAAKbWVhc3VyZSBtZSgAAAAEAAAABP83R08AAAABQUAAAIUAAAAwQUAAAEM2AAC/gAAAv4AA" +
            "AAAAAACbAAAAMQAAADAAAAAAKAAAAAIAAAAE//uMAFEAAAAyAAAAA/+AADFBQAAA/7EAASpBQAAAQzoAAP+AADJDQAAAsgT/gAAxQaAAACgAAAACAAAA" +
            "BP+OJKouQz4AAEM9AABAoAAA1g=="
    )
}
