package io.github.jamesgoodwin.remotecompose.fixtures

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/anim.rc`, generated by `buildAnimSample()` in `Main.kt` via
 * `./gradlew :tools:rc-writer:run --args="anim"`: four `FloatExpression` records driven by
 * `CONTINUOUS_SEC`, one with a cubic `FloatAnimation`. `AnimFixtureTest` asserts the values at
 * given times; this copy lets the device demos show the document actually moving.
 */
@OptIn(ExperimentalEncodingApi::class)
val ANIM_RC_BYTES: ByteArray by lazy {
    Base64.decode(
        "AAAAAAEAAAABAAAAAAAAAMgAAADIAAAAAAAAAABmAAAAKgAAAARhbmltZwAAACpRAAAAKwAAAAj/gAABQAAAAP+xAAP/sQASQnAAAP+xAANCyAAA/7EA" +
            "ASgAAAACAAAABP8eiOUu/4AAK0IgAABBgAAAUQAAACwAAAAFQEAAAECAAAD/sQAvQIAAAP+xAAMoAAAAAgAAAAT/Q6BHLkIgAABCyAAA/4AALFEAAAAt" +
            "AAEABv+AAAH/sQAOQAAAAP+xAAVCyAAA/7EAAz8AAABRAAAALgAAAAP/gAAtQiAAAP+xAAEoAAAAAgAAAAT/5Tk1Kv+AAC1DDAAA/4AALkMqAACHAAAA" +
            "L/+AAAEAAgACAAAQACgAAAAEAAAABP8AAAAAAAABQWAAAIUAAAAvQsgAAENDAAC/gAAAv4AAAAAAAAA=",
    )
}
