package io.github.jamesgoodwin.remotecompose.fixtures

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/paint.rc`, generated by `buildPaintSample()` in `Main.kt` via
 * `./gradlew :tools:rc-writer:run --args="paint"`. Exercises every `PaintBundle` attribute the
 * renderer decodes: stroke style/width/cap/join, cumulative commits, alpha, text size and
 * typeface, linear/radial/sweep gradients, shader clearing, color-pool ids, fill-and-stroke, and
 * paint state scoped to a component. `PaintFixtureTest` asserts the decoded structure; this copy
 * exists so the iOS and Android demos can render the same bytes for a visual cross-check.
 */
@OptIn(ExperimentalEncodingApi::class)
val PAINT_RC_BYTES: ByteArray by lazy {
    Base64.decode(
        "AAAAAAEAAAABAAAAAAAAAMgAAADIAAAAAAAAAABmAAAAKgAAAAVwYWludGcAAAAqKAAAAAcAAAAE/+U5NQABAAgAAAAFQMAAAAABAAcAAQAPKkFAAABB" +
            "QAAAQnAAAEJwAAAoAAAAAQAAAAguQrQAAEIQAABBoAAAKAAAAAQAAAAE/x6I5QAAAAw/AAAAKkKgAABB0AAAQwwAAEI4AAAoAAAABQAAAAT/AAAAAAAA" +
            "BUCAAAAAAgAHL0MWAABBoAAAQz4AAEJwAAAoAAAAAgAAAAFBwAAAZgAAACsAAAADQmlnhQAAACtBQAAAQrQAAL+AAAC/gAAAAAAAACgAAAAEAAAAAUEg" +
            "AAAKvAAQAAAAA2YAAAAsAAAACWJvbGQgbW9ub4UAAAAsQowAAEKsAAC/gAAAv4AAAAAAAAAoAAAADAAAAAsAAAAC//8AAP8AAP8AAAACAAAAAD+AAABB" +
            "QAAAQtwAAEK4AABC3AAAAAAAACpBQAAAQsgAAEK4AABDAgAAKAAAAAkAAQALAAAAAv//////Q6BHAAAAAEMMAABC5gAAQcgAAAAAAAAuQwwAAELmAABB" +
            "yAAAKAAAAAkAAgALAAAABP//AAD/AP8A/wAA////AAAAAAAAQlAAAEMlAAAqQUAAAEMMAABCuAAAQz4AAIoAAAAt/9UA+SgAAAAEAAAACQAAAAAAAAAT" +
            "AAAALSpC3AAAQwwAAEM+AABDHgAAKAAAAAQAAgAIAAAABUDAAAAAAgAPKkLwAABDKgAAQzQAAEM8AADK/////v////8AAAAAAAAAAMn////9KAAAAAMA" +
            "AAAE/0OgRwAAAAgqQyAAAEKEAABDPgAAQqAAANbWLkMWAABCrAAAQMAAAA==",
    )
}
