package io.github.jamesgoodwin.remotecompose.fixtures

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/shader.rc`, generated by `buildShaderSample()` in `Main.kt` via
 * `./gradlew :tools:rc-writer:run --args="shader"`.
 *
 * The demo's shader page draws it, and the tests read the same bytes; `PayloadDriftTest` checks
 * they still match the file.
 */
@OptIn(ExperimentalEncodingApi::class)
val SHADER_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAAHgAAAB4AAAAAAAAAABmAAAAKgAAAAZzaGFkZXJnAAAAKigAAAACAAAABP8eiOUqQQAAAEEAAABCUAAAQlAAAGYAAAArAAAApXVu" +
            "aWZvcm0gZmxvYXQyIGlSZXNvbHV0aW9uOwp1bmlmb3JtIGludCBpU3RlcHM7CmhhbGY0IG1haW4oZmxvYXQyIGNvb3JkKSB7CiAgZmxvYXQyIHV2ID0gY29v" +
            "cmQgLyBpUmVzb2x1dGlvbjsKICByZXR1cm4gaGFsZjQodXYueCwgdXYueSwgZmxvYXQoaVN0ZXBzKSAvIDguMCwgMS4wKTsKfWUAAAAsAAAAAgAAAAIAAABL" +
            "iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAEklEQVR4XmP4z8AARDDwn+E/ACLvA/14qpnZAAAAAElFTkSuQmCCLQAAAC0AAAArAAEBAQAA" +
            "AAtpUmVzb2x1dGlvbgAAAAJC8AAAQvAAAAAAAAZpU3RlcHMAAAABAAAABAAAAAhpVGV4dHVyZQAAACwoAAAAAgAAAAkAAAAtKkJwAABBAAAAQuAAAEJwAAAo" +
            "AAAABgAAAAkAAAAAAAAACQAAAAAAAAAE/0OgRy5CcAAAQrQAAEGgAAA="
    )
}
