package io.github.jamesgoodwin.remotecompose

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/attributes.rc`, generated by `buildAttributesSample()` in `Main.kt`
 * via `./gradlew :tools:rc-writer:run --args="attributes"`: four bars whose lengths are read off
 * a string and a bitmap through `ATTRIBUTE_TEXT` and `ATTRIBUTE_IMAGE`.
 *
 * No demo page carries this one, so it lives here for [fixture]; `PayloadDriftTest` checks it
 * still matches the file.
 */
@OptIn(ExperimentalEncodingApi::class)
val ATTRIBUTES_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAASwAAADIAAAAAAAAAABmAAAAKgAAAAphdHRyaWJ1dGVzZwAAACpmAAAAKwAAAAptZWFzdXJlIG1lZQAAACwAAAAYAAAADAAAAFyJ" +
            "UE5HDQoaCgAAAA1JSERSAAAAGAAAAAwIBgAAAHgwfXUAAAAjSURBVHheY7D0XP2flpgBXYDaeNQCgnjUAoJ41AKCmOYWAADbgHGfgwxxiQAAAABJRU5ErkJg" +
            "gigAAAAEAAAABP8bGx8AAAABQZAAACsAAAArAAAAAP////8AAAAAAAAAAEGgAABB8AAAAKoAAAAtAAAAKwAAAACqAAAALgAAACsABgAAqwAAAC8AAAAsAAAA" +
            "AKsAAAAwAAAALAABAABRAAAAMQAAAAP/gAAuQSAAAP+xAANRAAAAMgAAAAP/gAAvQIAAAP+xAANRAAAAMwAAAAP/gAAwQIAAAP+xAAMoAAAAAgAAAAT/Hojl" +
            "UQAAADQAAAAD/4AALUGgAAD/sQABKkGgAABCSAAA/4AANEKMAAAoAAAAAgAAAAT/Q6BHUQAAADUAAAAD/4AAMUGgAAD/sQABKkGgAABCqAAA/4AANULQAAAo" +
            "AAAAAgAAAAT/5Tk1UQAAADYAAAAD/4AAMkGgAAD/sQABKkGgAABC7AAA/4AANkMKAAAoAAAAAgAAAAT/jiSqUQAAADcAAAAD/4AAM0GgAAD/sQABKkGgAABD" +
            "GAAA/4AAN0MsAAA="
    )
}
