package io.github.jamesgoodwin.remotecompose

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/easing.rc`, generated by `buildEasingSample()` in `Main.kt` via
 * `./gradlew :tools:rc-writer:run --args="easing"`: one stepping target eased by the standard
 * cubic, the bounce, the elastic and a spline given its own shape, each driving a bar's
 * right edge.
 *
 * No demo page carries this one, so it lives here for [fixture]; `PayloadDriftTest` checks it
 * still matches the file.
 */
@OptIn(ExperimentalEncodingApi::class)
val EASING_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAASwAAADIAAAAAAAAAABmAAAAKgAAAAZlYXNpbmdnAAAAKlEAAAArAAAABv+AAAH/sQAOQAAAAP+xAAVCyAAA/7EAA1EAAAAsAAAA" +
            "A/+AACtCIAAA/7EAASgAAAACAAAABP8eiOUqQiAAAEGgAAD/gAAsQjAAAFEAAAAtAAIABv+AAAH/sQAOQAAAAP+xAAVCyAAA/7EAAz+AAAAAAAANUQAAAC4A" +
            "AAAD/4AALUIgAAD/sQABKAAAAAIAAAAE/0OgRypCIAAAQnAAAP+AAC5CqAAAUQAAAC8AAgAG/4AAAf+xAA5AAAAA/7EABULIAAD/sQADP4AAAAAAAA5RAAAA" +
            "MAAAAAP/gAAvQiAAAP+xAAEoAAAAAgAAAAT/5Tk1KkIgAABCyAAA/4AAMEL4AABRAAAAMQAHAAb/gAAB/7EADkAAAAD/sQAFQsgAAP+xAAM/gAAAAAQADAAA" +
            "AAA/gAAAPwAAAD+AAAAAAAAAUQAAADIAAAAD/4AAMUIgAAD/sQABKAAAAAIAAAAE/44kqipCIAAAQwwAAP+AADJDJAAA"
    )
}
