package io.github.jamesgoodwin.remotecompose

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/hostactions.rc`, generated by `buildHostActionsSample()` in
 * `Main.kt` via `./gradlew :tools:rc-writer:run --args="hostactions"`: three buttons, one for
 * each way a document can ask the host to do something.
 *
 * No demo page carries this one, so it lives here for [fixture]; `PayloadDriftTest` checks it
 * still matches the file.
 */
@OptIn(ExperimentalEncodingApi::class)
val HOSTACTIONS_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAASwAAADIAAAAAAAAAABmAAAAKgAAAAtob3N0YWN0aW9uc2cAAAAqvQAAACsAAAAAAAAAQAAHDhUcIyoxOD9GTVRbYmlwd36FjJOa" +
            "oaivtr3Ey9LZ4Ofu9fwDChEYHyYtNDtCSVBXXmVsc3qBiI+WnaSrsrlmAAAALAAAAAhza3UtNDQxN1AAAAAtQUgAAMz////+/////wAAAAEAAAAEQSAAABAA" +
            "AAABf8AAAEMAAAABf8AAADcAAAAAAAAAAAAAAAAAAAAAP4AAAD+AAAA/gAAAP4AAAAAAAAA6QYAAAEGAAABBgAAAQYAAAMn////9yv////z/////AAAAAQAA" +
            "AAIQAAAAAX/AAABDAAAAAEIgAAA2QaAAAEGgAABBoAAAQaAAADcAAAAAAAAAAAAAAAAAAAAAPfDw8T8IiIk/ZeXmP4AAAAAAAAA70QAAAAfWyf////tmAAAA" +
            "LgAAAAVQbGFpbmYAAAAvAAAAAND////6/////wAAAC7/////QWAAAAAAAABELwAAAAAALwABAAEAAAABAAAAAcn////51tbW1sr////4/////wAAAAEAAAAC" +
            "EAAAAAF/wAAAQwAAAABCIAAANkGgAABBoAAAQaAAAEGgAAA3AAAAAAAAAAAAAAAAAAAAAD6Ghoc/IKChPo6Ojz+AAAAAAAAAO9gAAAAJAAAALNbJ////92YA" +
            "AAAwAAAADVdpdGggbWV0YWRhdGHQ////9v////8AAAAw/////0FgAAAAAAAARC8AAAAAAC8AAQABAAAAAQAAAAHJ////9dbW1tbK////9P////8AAAABAAAA" +
            "AhAAAAABf8AAAEMAAAAAQiAAADZBoAAAQaAAAEGgAABBoAAANwAAAAAAAAAAAAAAAAAAAAA/ZeXmPmTk5T5U1NU/gAAAAAAAADtmAAAAMQAAAAlhZGRUb0Nh" +
            "cnTSAAAAMQAAAAAAAAAt1sn////zZgAAADIAAAAFTmFtZWTQ////8v////8AAAAy/////0FgAAAAAAAARC8AAAAAAC8AAQABAAAAAQAAAAHJ////8dbW1tbW" +
            "1g=="
    )
}
