package io.github.jamesgoodwin.remotecompose

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/named.rc`, generated by `buildNamedSample()` in `Main.kt` via
 * `./gradlew :tools:rc-writer:run --args="named"`: a card whose title, amount, accent colour and
 * count are all named through `NAMED_VARIABLE`, for a host to fill in.
 *
 * No demo page carries this one, so it lives here for [fixture]; `PayloadDriftTest` checks it
 * still matches the file.
 */
@OptIn(ExperimentalEncodingApi::class)
val NAMED_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAASwAAAC0AAAAAAAAAABmAAAAKgAAAAVuYW1lZGcAAAAqiQAAACsAAAAAAAAABXRpdGxlZgAAACsAAAANQXdhaXRpbmcgaG9zdIkA" +
            "AAAsAAAAAQAAAAZhbW91bnRQAAAALAAAAACKAAAALf9nUKSJAAAALQAAAAIAAAAGYWNjZW50iQAAAC4AAAAEAAAABWNvdW50jAAAAC4AAAAAzP////7/////" +
            "AAAAAQAAAARBAAAAEAAAAAF/wAAAQwAAAAF/wAAANwAAAAAAAAAAAAAAAAAAAAA/gAAAP4AAAD+AAAA/gAAAAAAAADpBgAAAQYAAAEGAAABBgAAAyf////1m" +
            "AAAALwAAAADQ/////P////8AAAAr/xsbH0GgAAAAAAAARC8AAAAAAC8AAQABAAAAAQAAAAHJ////+9bWhwAAADD/gAAsAAMAAgAAAADQ////+v////8AAAAw" +
            "/0RGT0FgAAAAAAAAQ8gAAAAAAC8AAQABAAAAAQAAAAHJ////+dbWyv////j/////AAAAAQAAAAIQAAAAAX/AAABDAAAAAEGAAADJ////9ygAAAACAAAAEwAA" +
            "AC1RAAAAMQAAAAP/gAAsQCuFH/+xAAMqAAAAAAAAAAD/gAAxQYAAANbW1tY="
    )
}
