package com.example.remotecompose

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/coretext.rc`, generated by `buildCoreTextSample()` in `Main.kt` via
 * `./gradlew :tools:rc-writer:run --args="coretext"`: two `CORE_TEXT` components, one of which
 * points at a `TEXT_STYLE`.
 *
 * No demo page carries this one, so it lives here for [fixture]; `PayloadDriftTest` checks it
 * still matches the file.
 */
@OptIn(ExperimentalEncodingApi::class)
val CORETEXT_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAASwAAADIAAAAAAAAAABmAAAAKgAAAAhjb3JldGV4dGcAAAAqZgAAACsAAAAJQ29yZSB0ZXh0ZgAAACwAAAAZc3R5bGVkIHRocm91" +
            "Z2ggVEVYVF9TVFlMRfIABQEAAAAtBUGwAAAHRC8AAAkAAAACGP/////M/////v////8AAAABAAAABEEAAAAQAAAAAX/AAABDAAAAAX/AAAA3AAAAAAAAAAAA" +
            "AAAAAAAAAD+AAAA/gAAAP4AAAD+AAAAAAAAAOkGAAABBgAAAQYAAAEGAAADJ/////e8AAAArAAUB/////AMAAAAABUGAAAAXAAAALRj/Gxsfyf////vW1u8A" +
            "AAAsAAUB////+gMAAAAABUGAAAAX/////xj/X1pmyf////nW1tbW"
    )
}
