package com.example.remotecompose

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/hostactions.rc`, generated by `buildHostActionsSample()` in
 * `Main.kt` via `./gradlew :tools:rc-writer:run --args="hostactions"`: three buttons, one for
 * each way a document can ask the host to do something.
 *
 * No demo page carries this one, so it lives here for [fixture]; `PayloadDriftTest` checks it
 * still matches the file.
 */
@OptIn(ExperimentalEncodingApi::class)
val HOSTACTIONS_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAASwAAADIAAAAAAAAAABmAAAAKgAAAAtob3N0YWN0aW9uc2cAAAAqZgAAACsAAAAIc2t1LTQ0MTdQAAAALEFIAADM/////v////8A" +
            "AAABAAAABEEgAAAQAAAAAX/AAABDAAAAAX/AAAA3AAAAAAAAAAAAAAAAAAAAAD+AAAA/gAAAP4AAAD+AAAAAAAAAOkGAAABBgAAAQYAAAEGAAADJ/////cr/" +
            "///8/////wAAAAEAAAACEAAAAAF/wAAAQwAAAABCIAAANkGgAABBoAAAQaAAAEGgAAA3AAAAAAAAAAAAAAAAAAAAAD3w8PE/CIiJP2Xl5j+AAAAAAAAAO9EA" +
            "AAAH1sn////7ZgAAAC0AAAAFUGxhaW5mAAAALgAAAADQ////+v////8AAAAt/////0FgAAAAAAAARC8AAAAAAC4AAQABAAAAAQAAAAHJ////+dbW1tbK////" +
            "+P////8AAAABAAAAAhAAAAABf8AAAEMAAAAAQiAAADZBoAAAQaAAAEGgAABBoAAANwAAAAAAAAAAAAAAAAAAAAA+hoaHPyCgoT6Ojo8/gAAAAAAAADvYAAAA" +
            "CQAAACvWyf////dmAAAALwAAAA1XaXRoIG1ldGFkYXRh0P////b/////AAAAL/////9BYAAAAAAAAEQvAAAAAAAuAAEAAQAAAAEAAAAByf////XW1tbWyv//" +
            "//T/////AAAAAQAAAAIQAAAAAX/AAABDAAAAAEIgAAA2QaAAAEGgAABBoAAAQaAAADcAAAAAAAAAAAAAAAAAAAAAP2Xl5j5k5OU+VNTVP4AAAAAAAAA7ZgAA" +
            "ADAAAAAJYWRkVG9DYXJ00gAAADAAAAAAAAAALNbJ////82YAAAAxAAAABU5hbWVk0P////L/////AAAAMf////9BYAAAAAAAAEQvAAAAAAAuAAEAAQAAAAEA" +
            "AAAByf////HW1tbW1tY="
    )
}
