package com.example.remotecompose

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/timeattr.rc`, generated by `buildTimeAttributeSample()` in `Main.kt`
 * via `./gradlew :tools:rc-writer:run --args="timeattr"`: parts read off a fixed moment through
 * `ATTRIBUTE_TIME`, each driving a bar.
 *
 * No demo page carries this one, so it lives here for [fixture]; `PayloadDriftTest` checks it
 * still matches the file.
 */
@OptIn(ExperimentalEncodingApi::class)
val TIMEATTR_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAASwAAADwAAAAAAAAAABmAAAAKgAAAAh0aW1lYXR0cmcAAAAqlAAAACsAAAGOGVLeCJQAAAAsAAABjhkb74isAAAALQAAACsABgAA" +
            "KAAAAAIAAAAE/x6I5VEAAAAuAAAAA/+AAC1BIAAA/7EAASpBIAAAQQAAAP+AAC5BsAAArAAAAC8AAAArAAcAACgAAAACAAAABP8eiOVRAAAAMAAAAAP/gAAv" +
            "QSAAAP+xAAEqQSAAAEHgAAD/gAAwQigAAKwAAAAxAAAAKwAIAAAoAAAAAgAAAAT/HojlUQAAADIAAAAD/4AAMUEgAAD/sQABKkEgAABCQAAA/4AAMkJ4AACs" +
            "AAAAMwAAACsACQAAKAAAAAIAAAAE/x6I5VEAAAA0AAAAA/+AADNBIAAA/7EAASpBIAAAQogAAP+AADRCpAAArAAAADUAAAArAAoAACgAAAACAAAABP8eiOVR" +
            "AAAANgAAAAP/gAA1QSAAAP+xAAEqQSAAAEKwAAD/gAA2QswAAKwAAAA3AAAAKwALAAAoAAAAAgAAAAT/HojlUQAAADgAAAAD/4AAN0EgAAD/sQABKkEgAABC" +
            "2AAA/4AAOEL0AACsAAAAOQAAACsADwAAKAAAAAIAAAAE/x6I5VEAAAA6AAAAA/+AADlBIAAA/7EAASpBIAAAQwAAAP+AADpDDgAArAAAADsAAAArAAQAAQAA" +
            "ACwoAAAAAgAAAAT/5Tk1UQAAADwAAAAD/4AAO0EgAAD/sQABKkEgAABDFgAA/4AAPEMkAAA="
    )
}
