package com.example.remotecompose

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Base64 of `tools/rc-writer/visibility.rc`, generated by `buildVisibilitySample()` in `Main.kt`
 * via `./gradlew :tools:rc-writer:run --args="visibility"`: a card the buttons hide and show,
 * fading either way through its `ANIMATION_SPEC`.
 *
 * No demo page carries this one, so it lives here for [fixture]; `PayloadDriftTest` checks it
 * still matches the file.
 */
@OptIn(ExperimentalEncodingApi::class)
val VISIBILITY_RC_BYTES: ByteArray by lazy {
    Base64.decode(
            "AAAAAAEAAAABAAAAAAAAASwAAADcAAAAAAAAAABmAAAAKgAAAAp2aXNpYmlsaXR5ZwAAACqMAAAAKwAAAAHM/////v////8AAAABAAAABEEgAAAQAAAAAX/A" +
            "AABDAAAAAX/AAAA3AAAAAAAAAAAAAAAAAAAAAD919fY/dfX2P3f3+D+AAAAAAAAAOkGAAABBgAAAQYAAAEGAAADJ/////WYAAAAsAAAAClZpc2liaWxpdHlm" +
            "AAAALQAAAADQ/////P////8AAAAs/xsbH0GgAAAAAAAARC8AAAAAAC0AAQABAAAAAQAAAAHJ////+9bWyv////r/////AAAAAQAAAAIQAAAAAX/AAABDAAAA" +
            "AEKAAADTAAAAKw4AAAABPszMzQAAAAE+zMzNAAAAAQAAAAAAAAABNkFAAABBQAAAQUAAAEFAAAA3AAAAAAAAAAAAAAAAAAAAAD7Ozs8+oKChPySkpT+AAAAA" +
            "AAAAyf////lmAAAALgAAAA5Ob3cgeW91IHNlZSBtZdD////4/////wAAAC7/////QXAAAAAAAABELwAAAAAALQABAAEAAAABAAAAAcn////31tbW1mYAAAAv" +
            "AAAAGGFuZCB0aGlzIHNpdHMgdW5kZXJuZWF0aND////2/////wAAAC//X1pmQUAAAAAAAABDyAAAAAAALQABAAEAAAABAAAAAcn////11tbL////9P////8A" +
            "AAABAAAAAkEAAAAQAAAAAX/AAADJ////88r////y/////wAAAAEAAAACEAAAAABC8AAAQwAAAABCEAAANkGQAABBkAAAQZAAAEGQAAA3AAAAAAAAAAAAAAAA" +
            "AAAAAD9o6Ok/Xt7fP3j4+T+AAAAAAAAA5TvUAAAAKwAAAADWyf////FmAAAAMAAAAARIaWRl0P////D/////AAAAMP8hAF1BUAAAAAAAAEQvAAAAAAAtAAEA" +
            "AQAAAAEAAAAByf///+/W1tbWyv///+7/////AAAAAQAAAAIQAAAAAELwAABDAAAAAEIQAAA2QZAAAEGQAABBkAAAQZAAADcAAAAAAAAAAAAAAAAAAAAAP2jo" +
            "6T9e3t8/ePj5P4AAAAAAAADlO9QAAAArAAAAAdbJ////7WYAAAAxAAAABFNob3fQ////7P////8AAAAx/yEAXUFQAAAAAAAARC8AAAAAAC0AAQABAAAAAQAA" +
            "AAHJ////69bW1tbW1tbW"
    )
}
